version: '3'
services:
  redis-server:
    image: 'redis'
  node-app:
     build:
      context: .
      dockerfile: Dockerfile
    image: 'xiexiaodocker/greenfield'
    restart: unless-stopped
    build: .
    ports:
      - '80:3000'
